CREATE ROLE owner;
GRANT ALL PRIVILEGES ON DATABASE "datingAgencyDb" TO owner;

CREATE ROLE admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;

CREATE ROLE operator;
GRANT SELECT, INSERT, DELETE, UPDATE ON ALL TABLES IN SCHEMA public TO operator;

CREATE ROLE guest;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO guest;